#:schema node_modules/wrangler/config-schema.json
name = "my-email-worker"
main = "src/index.ts"
compatibility_date = "2024-10-11"
compatibility_flags = [ "nodejs_compat" ]

[observability]
enabled = true

[vars]
EMAIL_WORKER_ADDRESS = "hello@kimptoncalls.com.au"
EMAIL_FORWARD_ADDRESS = "eddie@kimpton-tech.com"

[[send_email]]
name = "SEND_EMAIL"
